name: icon_craft
description: "IconCraft allows developers to create richer iconography with the ability to combine two icons into a single widget"
version: 0.1.0
homepage: https://github.com/vicenterusso/icon_craft
repository: https://github.com/vicenterusso/icon_craft/icons_plus
issue_tracker: https://github.com/vicenterusso/icon_craft/icons_plus/issues


environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0